// Ready-made sample businesses. Pick one in Setup, change the details, and share it as a demo.
// Everything here is made-up sample data.

export const TEMPLATES = {
  restaurant: {
    type: 'restaurant',
    name: 'Sharma Ji Ka Dhaba',
    city: 'Ludhiana',
    address: 'Shop 12, Ferozepur Road, near Bus Stand, Ludhiana',
    timings: 'Roz 11 AM se 11 PM. Diwali ke din band.',
    phone: '98765 43210',
    catalog: [
      'Dal Makhani - 180',
      'Paneer Butter Masala - 220',
      'Shahi Paneer - 230',
      'Kadhai Chicken (half) - 260',
      'Butter Chicken (half) - 280',
      'Mix Veg - 160',
      'Jeera Rice - 120',
      'Tandoori Roti - 15',
      'Butter Naan - 40',
      'Lassi (meethi/namkeen) - 60',
      'Special Thali (dal, sabzi, paneer, 4 roti, rice, salad) - 250',
    ].join('\n'),
    info: [
      'Home delivery 4 km tak. ₹300 se upar ka order free delivery, warna ₹30.',
      'Delivery mein 35-45 minute lagte hain.',
      'Payment: Cash ya UPI (delivery pe).',
      'Aaj ka special: Sarson da saag + makki di roti - 190 (sirf sardiyon mein).',
      'Party orders (20+ log) ke liye ek din pehle bataiye.',
    ].join('\n'),
    language: 'hinglish',
    greeting: '',
  },
  kirana: {
    type: 'kirana',
    name: 'Gupta General Store',
    city: 'Chandigarh',
    address: 'SCO 44, Sector 22-C Market, Chandigarh',
    timings: 'Roz 7 AM se 10 PM',
    phone: '98140 12345',
    catalog: [
      'Aashirvaad Atta 10 kg - 480',
      'Fortune Sunflower Oil 1 L - 165',
      'Tata Salt 1 kg - 28',
      'Amul Butter 500 g - 285',
      'Toor Dal 1 kg - 170',
      'Basmati Rice 5 kg - 650',
      'Amul Taaza Doodh 1 L - 56',
      'Maggi 12 pack - 168',
      'Surf Excel 1 kg - 140',
    ].join('\n'),
    info: [
      'Free home delivery Sector 15-24 mein, ₹500 se upar.',
      'Order 1 ghante mein pahunch jaata hai.',
      'UPI, cash, ya mahine ka khata (purane customers).',
      'List mein nahi hai to bhi poochiye - zyada tar saamaan milta hai, rate owner confirm karenge.',
    ].join('\n'),
    language: 'hinglish',
    greeting: '',
  },
  salon: {
    type: 'salon',
    name: 'Glow Unisex Salon',
    city: 'Mohali',
    address: 'Booth 7, Phase 7 Market, Mohali',
    timings: 'Tuesday se Sunday, 10 AM se 8 PM. Monday band.',
    phone: '99887 66554',
    catalog: [
      'Haircut (men) - 200',
      'Haircut (women) - 500',
      'Beard styling - 100',
      'Hair colour (global) - 1500 se shuru',
      'Facial (fruit) - 700',
      'Facial (gold) - 1200',
      'Threading - 50',
      'Manicure + Pedicure - 900',
      'Bridal makeup - 15000 se shuru (trial alag)',
    ].join('\n'),
    info: [
      'Appointment pe wait nahi karna padta. Walk-in bhi chalta hai par wait ho sakta hai.',
      'Har slot 30 minute ka. Last appointment 7:30 PM.',
      'Weekdays mein 10% off (Tuesday-Thursday).',
      'UPI / card / cash.',
    ].join('\n'),
    language: 'hinglish',
    greeting: '',
  },
  clinic: {
    type: 'clinic',
    name: 'Dr. Mehta Family Clinic',
    city: 'Patiala',
    address: '22, Leela Bhawan Market, Patiala',
    timings: 'Somvar-Shanivar: subah 9-1, shaam 5-8. Ravivar band.',
    phone: '0175 2201234',
    catalog: [
      'General consultation - 400',
      'Follow-up (7 din ke andar) - 200',
      'BP / sugar check - 100',
      'Home visit (5 km tak) - 1000',
    ].join('\n'),
    info: [
      'Dr. R. K. Mehta, MBBS, MD (Medicine). 20 saal ka experience.',
      'Appointment token system hai - time pe aane se wait kam hota hai.',
      'Lab test ke liye paas mein partner lab hai, report 24 ghante mein.',
      'Emergency ke liye clinic ka intezaar na karein - 112 call karein ya nazdeeki hospital jaayein.',
    ].join('\n'),
    language: 'hinglish',
    greeting: '',
  },
  coaching: {
    type: 'coaching',
    name: 'Bright Future Classes',
    city: 'Jalandhar',
    address: '2nd floor, Model Town Market, Jalandhar',
    timings: 'Somvar-Shanivar, 3 PM se 8 PM. Office: 11 AM se 8 PM.',
    phone: '97800 11223',
    catalog: [
      'Class 9-10 Maths + Science - 2500 / mahina',
      'Class 11-12 Physics / Chemistry / Maths (har subject) - 2000 / mahina',
      'Class 11-12 PCM combo - 5000 / mahina',
      'Spoken English (3 mahine) - 6000 total',
      'Registration fee (ek baar) - 500',
    ].join('\n'),
    info: [
      'Har batch mein maximum 15 bachche.',
      '2 free demo classes - pasand aaye to admission.',
      'Har mahine test aur parents meeting.',
      'Fees UPI / cash, mahine ki 10 tareekh tak.',
    ].join('\n'),
    language: 'hinglish',
    greeting: '',
  },
}
